--ALTER TABLE SIGCX ADD TIPO VARCHAR(1);

SET TERM ^ ;
CREATE OR ALTER PROCEDURE REG_SIGCX_BX_AUTO (
    TIPO VARCHAR(1),  -- A - lancamento automatico 
    CTRLDCTO Double precision,
    BANCO Varchar(10),
    DATA Timestamp,
    FILIAL Double precision,
    CODIGO Varchar(10),
    DCTO Varchar(15),
    VENDEDOR Varchar(10),
    VCTO Timestamp,
    VALOR Double precision,
    CLIFOR Double precision,
    HISTORICO Varchar(50),
    PRTSERIE Varchar(10),
    ORDEM Integer,
    DCTOOK Varchar(1),
    /* 20/01/2021 */
    OLDDCTO VARCHAR(15),
    CUPOMHR VARCHAR(8),
    CRIADOR_REGISTRO VARCHAR(10) )
RETURNS (
    CTRL Double precision )
AS
BEGIN
  INSERT INTO SIGCX (TIPO,
     BANCO,CLIFOR,CODIGO,CONTROL,DATA,DATA_,
     DCTO,DESCTOTAL,DIASBLOQ,EMITENTE,FILIAL,HISTORICO,
     HIST_, PRTSERIE,REGISTRADO,VALOR,VALOR_,VCTO,
     VENDEDOR,DCTOOK,COMPENSADO,ORDEM,DTCONTABIL,OLDDCTO,CUPOMHR,CRIADOR_REGISTRO  )
    VALUES(:TIPO,
     :BANCO,:CLIFOR,:CODIGO,:CTRLDCTO,:DATA,:DATA,
     :DCTO,0,0,'',:FILIAL,:HISTORICO,
     SUBSTRING(:HISTORICO FROM 1 FOR 34), :PRTSERIE,'N',:VALOR,:VALOR,:VCTO,
     :VENDEDOR,:DCTOOK,'N',:ORDEM, :DATA, :OLDDCTO, :CUPOMHR,:CRIADOR_REGISTRO);
  CTRL = CTRLDCTO;
  SUSPEND;

END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE REG_SIGCX_BX_AUTO TO  PUBLICWEB;
--ROlLBACK WORK ;


SET TERM ^ ;

CREATE OR ALTER PROCEDURE PROC_PAGAMENTO_CONTA
 ( P_FILIAL numeric(10,0), 
   P_DATA timestamp, 
   P_CTRL_ID numeric(15,0 ),
   P_CLIFOR numeric(15,0),
   V_CONTA VARCHAR(10),
   V_VALORORIGINAL NUMERIC(15,2),
   V_DATAPGTO timestamp,
   V_DCTOPGTO VARCHAR(10),
   V_HISTORICO VARCHAR(50),
   V_DCTOOK VARCHAR(1),
   V_PAGO NUMERIC(15,2),
   V_JUROS NUMERIC(15,2),
   V_DESP NUMERIC(15,2),
   V_DESC NUMERIC(15,2),
   V_OUTROS NUMERIC(15,2) ,
   V_USUARIO VARCHAR(10)
 )
RETURNS 
 (ORDEM INTEGER, CONTROL NUMERIC(15,0),CODIGO VARCHAR(10),HISTORICO VARCHAR(50), CONTROLBX NUMERIC(15,0), valor numeric(15,2) )
AS 
DECLARE VARIABLE LValor numeric(15,2); 
DECLARE VARIABLE LDCTO VARCHAR(10);
DECLARE VARIABLE LVENDEDOR VARCHAR(10);
DECLARE VARIABLE LPRTSERIE VARCHAR(10);
DECLARE VARIABLE ID NUMERIC(15,0);
DECLARE VARIABLE CONTA INTEGER;
DECLARE VARIABLE LTIPO VARCHAR(1);
BEGIN
  CONTA = 0;
  LVALOR = :V_VALORORIGINAL + :V_JUROS + :V_DESP + :V_OUTROS - :V_DESC;
  IF (LVALOR <> :V_PAGO) THEN
    EXCEPTION ERRO 'Valor original x pago inconsistente ['||:LVALOR||']';
    
  SELECT ID, VALOR,CODIGO,DCTO,CONTROL,TIPO FROM SIGFLU
  WHERE FILIAL=:p_filial AND 
        DATA = :p_DATA AND
        CTRL_ID = :P_CTRL_ID and
        CLIFOR = :p_CLIFOR AND
        COALESCE(BANCO,'') = ''
  INTO :ID, :VALOR,:CODIGO,:LDCTO,:CONTROL, :LTIPO;      
  
  IF (:VALOR IS NULL) then
    EXCEPTION ERRO  'Documento nao encontrado';
  
  if (:valor <> :V_VALORORIGINAL) THEN
    EXCEPTION ERRO 'Valor inconsistente';
  
  select numero from obter_id('CTRLDCTO')
  into :controlbx;

  ORDEM = 1;
  
  HISTORICO = :V_HISTORICO;
  SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO(:LTIPO,:CONTROLBX,
   :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
   :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:V_VALORORIGINAL,
   :P_CLIFOR,:HISTORICO,:LPRTSERIE,
   :ORDEM,COALESCE(:V_DCTOOK,'N'),'','',:V_USUARIO )
   INTO :CONTROLBX;

  IF (ROW_COUNT=0) THEN
    EXCEPTION ERRO 'Nao efetuou o lancamento de liquidacao na conta';

   
  CONTA = CONTA + ROW_COUNT;
  suspend;
   
  if (V_JUROS<>0) then
  begin
   ordem = ordem +1;
   HISTORICO = 'PAGAMENTO JUROS TITULO';
   CODIGO = '221';
   VALOR = :V_JUROS;
   SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO('A',:CONTROLBX,
     :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
     :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:VALOR,
     :P_CLIFOR,:HISTORICO,:LPRTSERIE,
     :ORDEM,COALESCE(:V_DCTOOK,'N'),'','',:V_USUARIO )
     INTO :CONTROLBX;
   CONTA = CONTA + ROW_COUNT;
   suspend;
  end 
   
  if (V_DESP<>0) then
  begin
   ordem = ordem +1;
   CODIGO = '990';
   VALOR = :V_DESP;
   HISTORICO = 'DESP NA LIQ. TITULO';
   SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO('A',:CONTROLBX,
     :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
     :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:VALOR,
     :P_CLIFOR,:HISTORICO,:LPRTSERIE,
     :ORDEM,COALESCE(:V_DCTOOK,'N'),'','',:V_USUARIO )
     INTO :CONTROLBX;
   CONTA = CONTA + ROW_COUNT;
   suspend;
  end 

  if (V_OUTROS<>0) then
  begin
   ordem = ordem +1;
   CODIGO = '990';
   VALOR = :V_OUTROS;
   HISTORICO = 'OUTRAS DESP. NA LIQ. TITULO';
   SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO('A',:CONTROLBX,
     :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
     :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:VALOR,
     :P_CLIFOR,:HISTORICO,:LPRTSERIE,
     :ORDEM,COALESCE(:V_DCTOOK,'N'),'','',:V_USUARIO )
     INTO :CONTROLBX;
   CONTA = CONTA + ROW_COUNT;
   suspend;
  end 

  if (V_DESC<>0) then
  begin
   ordem = ordem +1;
   CODIGO = '221';
   VALOR = -:V_DESC;
   HISTORICO = 'OUTROS DESC. NA LIQ. TITULO';
   SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO('A',:CONTROLBX,
     :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
     :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:VALOR,
     :P_CLIFOR,:HISTORICO,:LPRTSERIE,
     :ORDEM,COALESCE(:V_DCTOOK,'N') ,'','',:V_USUARIO)
     INTO :CONTROLBX;
   CONTA = CONTA + ROW_COUNT;
   suspend;
  end 

   
  IF (CONTA > 0  ) THEN
  BEGIN
    UPDATE SIGFLU 
    SET 
      CONTROLBX = :CONTROLBX,
      BANCO = :V_CONTA,
      DTPGTO = :V_DATAPGTO
    WHERE ID = :ID;
    
    IF (ROW_COUNT=0) then
      EXCEPTION ERRO 'Nao foi possivel liquidar o documento, tente novamente.';
  END
  
  
END^


SET TERM ; ^



SET TERM ^ ;

CREATE OR ALTER PROCEDURE PROC_RECEBIMENTO_CONTA
 ( P_FILIAL numeric(10,0), 
   P_DATA timestamp, 
   P_CTRL_ID numeric(15,0 ),
   P_CLIFOR numeric(15,0),
   V_CONTA VARCHAR(10),
   V_VALORORIGINAL NUMERIC(15,2),
   V_DATAPGTO timestamp,
   V_DCTOPGTO VARCHAR(10),
   V_HISTORICO VARCHAR(50),
   V_DCTOOK VARCHAR(1),
   V_PAGO NUMERIC(15,2),
   V_JUROS NUMERIC(15,2),
   V_DESP NUMERIC(15,2),
   V_DESC NUMERIC(15,2),
   V_OUTROS NUMERIC(15,2) ,
   V_USUARIO VARCHAR(10)
 )
RETURNS 
 (ORDEM INTEGER, CONTROL NUMERIC(15,0),CODIGO VARCHAR(10),HISTORICO VARCHAR(50), CONTROLBX NUMERIC(15,0), valor numeric(15,2) )
AS 
DECLARE VARIABLE LValor numeric(15,2); 
DECLARE VARIABLE LDCTO VARCHAR(10);
DECLARE VARIABLE LVENDEDOR VARCHAR(10);
DECLARE VARIABLE LPRTSERIE VARCHAR(10);
DECLARE VARIABLE ID NUMERIC(15,0);
DECLARE VARIABLE CONTA INTEGER;
DECLARE VARIABLE LTIPO VARCHAR(1);
BEGIN
  CONTA = 0;
  LVALOR = :V_VALORORIGINAL + :V_JUROS + :V_DESP + :V_OUTROS - :V_DESC;
  IF (LVALOR <> :V_PAGO) THEN
    EXCEPTION ERRO 'Valor original x pago inconsistente ['||:LVALOR||']';
    
  SELECT ID, VALOR,CODIGO,DCTO,CONTROL,TIPO FROM SIGFLU
  WHERE FILIAL=:p_filial AND 
        DATA = :p_DATA AND
        CTRL_ID = :P_CTRL_ID and
        CLIFOR = :p_CLIFOR AND
        COALESCE(BANCO,'') = ''
  INTO :ID, :VALOR,:CODIGO,:LDCTO,:CONTROL,:LTIPO;      
  
  IF (:VALOR IS NULL) then
    EXCEPTION ERRO  'Documento nao encontrado';
  
  if (:valor <> :V_VALORORIGINAL) THEN
    EXCEPTION ERRO 'Valor inconsistente';
  
  select numero from obter_id('CTRLDCTO')
  into :controlbx;

  ORDEM = 1;
  
  HISTORICO = :V_HISTORICO;
  SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO(:LTIPO,:CONTROLBX,
   :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
   :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:V_VALORORIGINAL,
   :P_CLIFOR,:HISTORICO,:LPRTSERIE,
   :ORDEM,COALESCE(:V_DCTOOK,'N'),'','',:V_USUARIO )
   INTO :CONTROLBX;

  IF (ROW_COUNT=0) THEN
    EXCEPTION ERRO 'Nao efetuou o lancamento de liquidacao na conta';

   
  CONTA = CONTA + ROW_COUNT;
  suspend;
   
  if (V_JUROS<>0) then
  begin
   ordem = ordem +1;
   HISTORICO = 'RECEBIMENTO JUROS TITULO';
   CODIGO = '121';
   VALOR = :V_JUROS;
   SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO('A',:CONTROLBX,
     :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
     :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:VALOR,
     :P_CLIFOR,:HISTORICO,:LPRTSERIE,
     :ORDEM,COALESCE(:V_DCTOOK,'N'),'','',:V_USUARIO )
     INTO :CONTROLBX;
   CONTA = CONTA + ROW_COUNT;
   suspend;
  end 
   
  if (V_DESP<>0) then
  begin
   ordem = ordem +1;
   CODIGO = '990';
   VALOR = -:V_DESP;
   HISTORICO = 'DESP NA LIQ. TITULO';
   SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO('A',:CONTROLBX,
     :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
     :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:VALOR,
     :P_CLIFOR,:HISTORICO,:LPRTSERIE,
     :ORDEM,COALESCE(:V_DCTOOK,'N'),'','',:V_USUARIO )
     INTO :CONTROLBX;
   CONTA = CONTA + ROW_COUNT;
   suspend;
  end 

  if (V_OUTROS<>0) then
  begin
   ordem = ordem +1;
   CODIGO = '990';
   VALOR = -:V_OUTROS;
   HISTORICO = 'OUTRAS DESP. NA LIQ. TITULO';
   SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO('A',:CONTROLBX,
     :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
     :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:VALOR,
     :P_CLIFOR,:HISTORICO,:LPRTSERIE,
     :ORDEM,COALESCE(:V_DCTOOK,'N'),'','',:V_USUARIO )
     INTO :CONTROLBX;
   CONTA = CONTA + ROW_COUNT;
   suspend;
  end 

  if (V_DESC<>0) then
  begin
   ordem = ordem +1;
   CODIGO = '121';
   VALOR = -:V_DESC;
   HISTORICO = 'OUTROS DESC. NA LIQ. TITULO';
   SELECT FIRST 1 CTRL FROM REG_SIGCX_BX_AUTO('A',:CONTROLBX,
     :V_CONTA,:V_DATAPGTO,:P_FILIAL,:CODIGO,
     :V_DCTOPGTO,:LVENDEDOR,:P_DATA,:VALOR,
     :P_CLIFOR,:HISTORICO,:LPRTSERIE,
     :ORDEM,COALESCE(:V_DCTOOK,'N') ,'','',:V_USUARIO)
     INTO :CONTROLBX;
   CONTA = CONTA + ROW_COUNT;
   suspend;
  end 

   
  IF (CONTA > 0  ) THEN
  BEGIN
    UPDATE SIGFLU 
    SET 
      CONTROLBX = :CONTROLBX,
      BANCO = :V_CONTA,
      DTPGTO = :V_DATAPGTO
    WHERE ID = :ID;
    
    IF (ROW_COUNT=0) then
      EXCEPTION ERRO 'Nao foi possivel liquidar o documento, tente novamente.';
  END
  
  
END^


SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE PROC_PAGAMENTO_CONTA TO  PUBLICWEB;
GRANT EXECUTE
 ON PROCEDURE PROC_RECEBIMENTO_CONTA TO  PUBLICWEB;


COMMIT WORK;

/*
SELECT * FROM PROC_PAGAMENTO_CONTA(
  5,'2019-12-21',7184594098393,1,
   '01',
   1000,
   CAST('TODAY' AS TIMESTAMP),
   '123',
   'PGATO',
   'S',
   1004,
   1,
   2,
   3,
   4 )
*/   
   