


grant select, update, insert on estoper to publicweb;
grant select, insert on estmvto to publicweb;

grant select,insert,update on ctprodsd_lote to publicweb;
grant select,insert,update on ctprodsd_serie to publicweb;
grant select,insert,update on ESTMVTO_DEMANDA_DIARIA to publicweb;
grant select,insert,update on SIGCAUT2_DATA_GRADE to publicweb;

grant execute  on procedure  ABRE_NOVOPRODUTO_ESTOQUE to publicweb;

grant execute  on procedure  REGISTRA_GRADE to publicweb;
grant execute  on procedure  REGISTRA_ESTOQUE to publicweb;
grant execute  on procedure  Reg_serie to publicweb;
grant execute  on procedure  Reg_lote to publicweb;


commit work;


SET TERM ^ ;

CREATE or alter TRIGGER tr_estmvto_before_pega_estoque FOR ESTMVTO
ACTIVE BEFORE INSERT POSITION 0
AS 
declare variable qt double precision;
BEGIN 
	/* enter trigger code here */ 
	select qestfin from ctprodsd
	where codigo=new.codigo and filial=new.filial
	into :qt;
	new.qestant = :qt;
END^

SET TERM ; ^ 



SET TERM ^ ;
CREATE OR ALTER PROCEDURE PROC_REG_ESTOQUE
returns
  (CONTA INT)
AS
DECLARE VARIABLE ID DOUBLE PRECISION;
declare VARIABLE DATA timestamp;
DECLARE VARIABLE FILIAL DOUBLE PRECISION;
DECLARE VARIABLE CODIGO VARCHAR(18);
DECLARE VARIABLE QTDE DOUBLE PRECISION;
DECLARE VARIABLE PRECO DOUBLE PRECISION;
DECLARE VARIABLE OPERACAO VARCHAR(10);
DECLARE VARIABLE CLIFOR DOUBLE PRECISION;
DECLARE VARIABLE DCTO VARCHAR(10);
DECLARE VARIABLE PRTSERIE VARCHAR(10);
DECLARE VARIABLE ORDEM DOUBLE PRECISION;
DECLARE VARIABLE NOME VARCHAR(50);
DECLARE VARIABLE VENDEDOR VARCHAR(10);
DECLARE VARIABLE VALOR DOUBLE PRECISION;
DECLARE VARIABLE PA DOUBLE PRECISION;
DECLARE VARIABLE ICMS DOUBLE PRECISION;
DECLARE VARIABLE IPI DOUBLE PRECISION;
DECLARE VARIABLE ISS DOUBLE PRECISION;
DECLARE VARIABLE NUMSERIE varchar(20); 
DECLARE VARIABLE NUMLOTE DOUBLE PRECISION;
DECLARE VARIABLE  OLDDCTO VARCHAR(10);
BEGIN
  -- PEGAR VENDAS E REGISTRAR ESTOQUE
  CONTA = 0;
  FOR SELECT first 500 ID FROM SIGCAUT2
  WHERE REGISTRADO='N' 
  INTO :ID
  DO
  BEGIN
   IN AUTONOMOUS transaction DO
   BEGIN
       SELECT NUMSERIE, NUMLOTE, OLDDCTO, PA,VENDEDOR,NOME,ORDEM, PRTSERIE,DCTO,OPERACAO,CLIFOR, 
         DATA,FILIAL,CODIGO,QTDE,PRECO,
         VALOR,ICMS,IPI,ISS FROM SIGCAUT2
       WHERE ID = :ID
       INTO :NUMSERIE, :NUMLOTE, :OLDDCTO, :PA,:VENDEDOR,:NOME,:ORDEM,:PRTSERIE,:DCTO, :OPERACAO,:CLIFOR,
         :DATA,:FILIAL,:CODIGO,:QTDE,:PRECO,VALOR,:ICMS,:IPI,:ISS;
       
       INSERT INTO ESTMVTO 
         (CONTROL,VENDEDOR,NOME,ORDEM,BdREGESTOQUE, PRTSERIE,DCTO,
           DATA,FILIAL,CODIGO,QTDE,PRECOBASE,PRECOLIQ,OPERACAO,CLIFOR,VALOR,PRECO_AQ,
           BRUTO,ICMS,IPI,ISS,CUSTO,PMEDIO,
           NUMSERIE, NUMLOTE, OLDDCTO)
         VALUES (:ID,:VENDEDOR,:NOME,:ORDEM,'1',:PRTSERIE,:DCTO,
           :DATA,:FILIAL,:CODIGO,:QTDE,:PRECO,:PRECO,:OPERACAO,:CLIFOR,:VALOR,:PA,
           :PRECO,:ICMS,:IPI,:ISS,:PA,:PA,
           :NUMSERIE, :NUMLOTE, :OLDDCTO );
       
       CONTA = CONTA + row_count;
       IF (ROW_COUNT>0) THEN
          UPDATE SIGCAUT2 SET REGISTRADO = 'S' WHERE ID = :ID;
       
   END
  
  END
  RDB$SET_CONTEXT('USER_TRANSACTION', 'CTX_ROWSAFFECTED', conta );
  SUSPEND;

END^
SET TERM ; ^


GRANT EXECUTE
 ON PROCEDURE PROC_REG_ESTOQUE TO  SYSDBA WITH GRANT OPTION;
 
GRANT EXECUTE
 ON PROCEDURE PROC_REG_ESTOQUE TO PUBLICWEB; 

